services:
  navidrome:
    image: deluan/navidrome:latest
    container_name: navidrome
    hostname: navidrome
    #user: 1000:1000 # UID:GID
    ports:
      - "4533:4533"
    restart: unless-stopped
    environment:
      # Optional: put your config options customization here. Examples:
      # ND_LOGLEVEL: debug
        ND_SCANSCHEDULE: 1h
        ND_LOGLEVEL: info
        ND_SESSIONTIMEOUT: 24h
        ND_AGENTS: "lastfm,spotify,deezer"
        ND_LASTFM_APIKEY: "ad7d5745feeeeb72c26f9e4120ba3fca"
        ND_LASTFM_SECRET: "97ca00fbfdf5945222f6b45daca46c1c"
        ND_SPOTIFY_ID: "8619ae2d3584454b9403a38afe2068ef"
        ND_SPOTIFY_SECRET: "0a91391754174b729c2aa45b8c777950"
        
    volumes:
      - "/home/felga/homelab/navidrome/data:/data"
      #- "/home/felga/homelab/navidrome/cache:/cache"
      - "/media/hddhomelab/Music:/music:ro"

volumes:
  navidrome-data: